name: 'Nightly build, versioned, and released oxidized container. UTC time.'
on:
  schedule:
    - cron: '20 5 * * *'

jobs:

  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: AS271
          base: master
          head: master

  docker:

    needs: sync

    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push to registries
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            as271/oxidized:${{ github.ref_name }}
            as271/oxidized:latest